version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/src
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the docker
          command: docker build -t munchy-api:latest .
      - deploy:
          name: Push to docker dev repository if MASTER
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then
                sudo pip install awscli --upgrade
                aws ecr get-login --no-include-email --region us-east-1 | bash -
                docker tag munchy-api:latest 806947599851.dkr.ecr.us-east-1.amazonaws.com/munchy:dev
                docker push 806947599851.dkr.ecr.us-east-1.amazonaws.com/munchy:dev
            fi
